defaults:
  - base
  - _self_

data_log_name: bespoke_stratos_17k

dataset_id_or_path: bespokelabs/Bespoke-Stratos-17k

dataset_configs:
  - all

completion_only_training: True
custom_start_of_response: ~
keep_columns: ~
add_dataset_indices: False

make_dataset_fn:
  _target_: custom_data.sft_data.load_formatted_sft_dataset
  process_line_fn:
    _target_: custom_data.sft_data.get_process_line_fn
    dataset_id_or_path: ${dataset_id_or_path}
  completion_only_training: ${completion_only_training}
  custom_start_of_response: ${custom_start_of_response}
  keep_columns: ${keep_columns}
  add_dataset_indices: ${add_dataset_indices}
